name: UpCode
on: push

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [CurrencyConverter, guess_my_number, Lab2, number_shape]
    env:
      CI_JOB_NAME: format
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: actions/checkout@v2
      - name: Setup repository
        run: |
          cd ${{ matrix.module }}
          flutter pub get
      - name: Format code
        run: |
          cd ${{ matrix.module }}
          flutter pub pub run --enable-asserts ci/bots/format.dart --set-exit-if-changed -n -l 120

  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [CurrencyConverter, guess_my_number, Lab2, number_shape]
    env:
      CI_JOB_NAME: analyze
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: actions/checkout@v2
      - name: Setup repository
        run: |
          cd ${{ matrix.module }}
          flutter pub get
      - name: Analyze code
        run: |
          cd ${{ matrix.module }}
          flutter pub pub run --enable-asserts ci/bots/analyze.dart