name: basic_phrases
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  assets_audio_player: ^2.0.13+1
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true


  assets:
    - assets/audio/masina.mp3
    - assets/audio/car.mp3
    - assets/audio/Silvester.mp3
    - assets/audio/Stallone.mp3
    - assets/audio/Marco.mp3
    - assets/audio/Polo.mp3
    - assets/audio/Maverick.mp3
    - assets/audio/goose.mp3
